site_url:
  ca: "https://moulanoviolencia.net"
  es: "https://muevelanoviolencia.net"
  en: "https://movenonviolence.net"
domain_language:
  ca: "moulanoviolencia"
  es: "muevelanoviolencia"
  en: "movenonviolence"
language_territory:
  ca: "ca_ES"
  es: "es_ES"
  en: "en_US"

markdown: kramdown

plugins:
  - jekyll-analytics

defaults:
  - scope:
      path: ""
      type: "units"
    values:
      layout: "unit"

collections:
  units:
    output: true
    permalink: /:path/

jekyll_analytics:
  GoogleAnalytics:
    id: UA-4283680-5
    anonymizeIp: false

exclude: ["README.md", "Gemfile.lock", "Gemfile"]
